name: Test Action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:


  test-npm-install:
    name: Test npm install with safe-chain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run Aikido Safe Chain action
        uses: ./
        with:
          minimum-package-age-hours: 48

      - name: Test npm install
        run: |
          npm install express
